"""Data preparation — quality filtering, deduplication, boilerplate removal."""
from __future__ import annotations

import hashlib
import re


class DataPrep:
    """
    Pre-ingestion quality filtering applied to all chunks before embedding.

    Filters:
    - Minimum length (skip near-empty chunks)
    - Boilerplate patterns (auto-generated files, license headers)
    - Exact deduplication via content hash
    - Language detection (skip non-English if configured)

    DataPrepToolkit integration point: swap internals with IBM's DataPrepToolkit
    pipeline for production-grade PII detection and quality scoring.
    """

    BOILERPLATE_PATTERNS = [
        r"^# auto-generated",
        r"^// generated by",
        r"^/\* \* \* .+ license",
        r"^package-lock\.json",
    ]

    def __init__(self, min_chars: int = 50) -> None:
        self.min_chars = min_chars
        self._seen_hashes: set[str] = set()

    def filter(self, chunks: list) -> list:
        return [c for c in chunks if self._keep(c)]

    def reset_dedup(self) -> None:
        self._seen_hashes.clear()

    def _keep(self, chunk) -> bool:
        text = chunk.text if hasattr(chunk, "text") else str(chunk)
        if len(text) < self.min_chars:
            return False
        if self._is_boilerplate(text):
            return False
        h = hashlib.sha256(text.encode()).hexdigest()
        if h in self._seen_hashes:
            return False
        self._seen_hashes.add(h)
        return True

    def _is_boilerplate(self, text: str) -> bool:
        first_line = text.strip().splitlines()[0].lower() if text.strip() else ""
        return any(re.match(p, first_line) for p in self.BOILERPLATE_PATTERNS)
